-- Partial schema mirror for JPA tests; live Supabase validation remains required.
CREATE TABLE shelters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_source VARCHAR(30), external_id VARCHAR(100), name VARCHAR(150) NOT NULL,
  phone VARCHAR(30), address VARCHAR(500), region_code VARCHAR(20),
  participation_status VARCHAR(20) NOT NULL, last_synced_at TIMESTAMP(6) WITH TIME ZONE,
  UNIQUE (external_source, external_id)
);
CREATE TABLE animals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shelter_id BIGINT REFERENCES shelters(id), origin VARCHAR(20) NOT NULL,
  name VARCHAR(100), description TEXT, species VARCHAR(20) NOT NULL, breed_name VARCHAR(100),
  sex VARCHAR(10) NOT NULL, neuter_status VARCHAR(10) NOT NULL,
  age_description VARCHAR(100), weight_kg DECIMAL(6,2), color VARCHAR(100), found_date DATE, found_place VARCHAR(500),
  care_status VARCHAR(30) NOT NULL, status_authority VARCHAR(20) NOT NULL,
  visibility VARCHAR(20) NOT NULL, consultation_enabled BOOLEAN NOT NULL
);
CREATE TABLE animal_external_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id BIGINT NOT NULL UNIQUE REFERENCES animals(id), source VARCHAR(30) NOT NULL,
  external_id VARCHAR(100) NOT NULL, notice_number VARCHAR(100),
  notice_start_date DATE, notice_end_date DATE, external_status VARCHAR(100), raw_payload JSONB NOT NULL,
  last_seen_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  last_synced_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  UNIQUE (source, external_id)
);
CREATE TABLE animal_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id BIGINT NOT NULL REFERENCES animals(id), source VARCHAR(20) NOT NULL,
  url VARCHAR(2048) NOT NULL, sort_order INTEGER NOT NULL
);
CREATE TABLE sync_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, request_scope JSONB NOT NULL,
  started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  finished_at TIMESTAMP(6) WITH TIME ZONE, last_successful_page INTEGER,
  fetched_count INTEGER NOT NULL, inserted_count INTEGER NOT NULL,
  updated_count INTEGER NOT NULL, failed_count INTEGER NOT NULL, error_summary TEXT
);
